#!/usr/bin/python3

DOMAIN = "mintbackup"
PATH = "/usr/share/linuxmint/locale"

import os
import gettext
import mintcommon.additionalfiles as additionalfiles

os.environ['LANGUAGE'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = "[Desktop Entry]\n"

suffix = """Exec=mintbackup
Icon=mintbackup
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Application;System;Settings
NotShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/mintbackup.desktop", prefix, _("Backup Tool"), _("Backup apps and files"), suffix)


prefix = "[Desktop Entry]\n"

suffix = """Exec=mintBackup
Icon=mintbackup
Terminal=false
Type=Application
Encoding=UTF-8
Categories=Qt;KDE;System;
X-KDE-StartupNotify=false
OnlyShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/kde4/mintbackup.desktop", prefix, _("Backup Tool"), _("Backup apps and files"), suffix, genericName=_("Backup apps and files"))
