#!/bin/bash

intltool-extract --type=gettext/glade usr/share/linuxmint/mintbackup/mintbackup.ui

xgettext --language=Python --keyword=_ --output=mintbackup.pot \
  usr/lib/linuxmint/mintbackup/mintbackup.py \
  generate_desktop_files.py \
  usr/share/linuxmint/mintbackup/mintbackup.ui.h
xgettext --language=PolkitPolicy --its=polkit.its --output=mintbackup.pot --join-existing usr/share/polkit-1/actions/*.policy

rm -f usr/share/linuxmint/mintbackup/mintbackup.ui.h
